hello-flask/studenst-flask/src/models/abstract_model.py
from pymongo.collection import Collection, ObjectId


class AbstractModel:
    _collection: Collection = None

    def __init__(self, data: dict) -> None:
        self.data = data

    def save(self):
        post_id = self._collection.insert_one(self.data)
        return str(post_id.inserted_id)

    def update(self, id: str):
        post_id = self._collection.update_one(
            {"_id": id},
            {"$set": self.data}
            )

        return post_id

    def delete(self):
        db_return = self._collection.delete_one({"_id": ObjectId(self.data)})
        return db_return

    @classmethod
    def find(cls, query: dict = {}):
        data = cls._collection.find(query)
        return [res for res in data]

    @classmethod
    def find_one(cls, query: str):
        data = cls._collection.find_one({"_id": ObjectId(query)})
        return data

hello-flask/studenst-flask/src/models/db.py
from pymongo import MongoClient
from os import environ

client = MongoClient(environ.get("MONGO_URL"))

db = client.student

hello-flask/studenst-flask/src/models/student_model.py
from .abstract_model import AbstractModel
from .db import db


class StudentModel(AbstractModel):
    _collection = db["students"]

    def __init__(self, json_data):
        super().__init__(json_data)

    def _get_all(self, query: dict = {}):
        students = self.find(query)
        return [str(student) for student in students]

    def _stringfy_id(self):
        self.data["_id"] = str(self.data["_id"])
        return str(self.data)

hello-flask/studenst-flask/src/app.py
from flask import Flask
from os import environ
from waitress import serve
from flask_bootstrap import Bootstrap5
from flask_wtf import CSRFProtect
import secrets
from controllers.students_controller import students_controller


app = Flask(__name__)
secret = secrets.token_urlsafe(16)
app.secret_key = secret
bootstrap = Bootstrap5(app)
csrf = CSRFProtect(app)


app.register_blueprint(students_controller, url_prefix="/students")


@app.route("/")
def hello_world():
    return "Hello World!"


def start_server(host: str = "0.0.0.0", port: int = 8000):
    if environ.get("FLASK_ENV") == "dev":
        return app.run(debug=True, host=host, port=port)
    serve(app, host=host, port=port)


if __name__ == "__main__":
    start_server()

hello-flask/studenst-flask/src/controllers/students_controller.py
from flask import Blueprint, jsonify, render_template, redirect, url_for
from models.student_model import StudentModel
from form.register import Register
from form.edit import Edit

students_controller = Blueprint("students", __name__)


@students_controller.route("/", methods=["GET"])
def student_index():
    student_db = StudentModel
    list = student_db.find()
    return render_template(
        "students.html", 
        app_name="Student List",
        students_list=list
        )


@students_controller.route("/register", methods=["GET", "POST"])
def student_register():
    form = Register()
    message = ""
    if form.validate_on_submit():
        name = form.name.data
        register = form.registration.data
        message = "SUCCESSFULL"
        student = StudentModel({"name": name, "registration": register})
        student.save()
    if message == "SUCCESSFULL":
        return redirect(url_for("students.student_index"))
    return render_template("register.html", form=form, message=message)


@students_controller.route("/edit/<student_id>", methods=["GET", "POST"])
def student_edit(student_id: str):
    student = StudentModel
    get_student = student.find_one(student_id)
    form = Edit()

    message = ""
    id = get_student["_id"]
    name = get_student["name"]

    if form.validate_on_submit():
        name = form.name.data
        update_name = StudentModel({"name": name})
        update_name.update(id)
        message = "SUCCESSFULL"

    if message == "SUCCESSFULL":
        return redirect(url_for("students.student_index"))

    return render_template("edit_student.html", form=form, name=name)


@students_controller.route("/delete/<student_id>", methods=["GET", "DELETE"])
def student_delete(student_id: str):
    message = ""
    student = StudentModel(student_id)
    student.delete()
    new_list = student.find()
    message = "SUCCESSFULL"
    if message == "SUCCESSFULL":
        return redirect(url_for("students.student_index"))
    return render_template(
        "students.html", app_name="Student List", students_list=new_list
    )

hello-flask/studenst-flask/src/templates/edit_student.html
{% from 'bootstrap5/form.html' import render_form %}

{% block title %}
Student Edit Registration
{% endblock %}

{% block content %}

<!--
	TIPS about using Bootstrap-Flask:
	https://github.com/helloflask/bootstrap-flask
	https://bootstrap-flask.readthedocs.io/
-->

<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-lg-auto mx-md-auto">
      <h1 class="pt-5 pb-2">Edit Registrarion</h1>
      <p class="pt-5"><strong>{{ name }}</strong></p>
        {{ render_form(form) }}
    </div>
  </div>
</div>
{% endblock %}

hello-flask/studenst-flask/src/templates/register.html
{% from 'bootstrap5/form.html' import render_form %}

{% block title %}
Student Registration
{% endblock %}

{% block content %}

<!--
	TIPS about using Bootstrap-Flask:
	https://github.com/helloflask/bootstrap-flask
	https://bootstrap-flask.readthedocs.io/
-->

<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-lg-auto mx-md-auto">

      <h1 class="pt-5 pb-2">Registration</h1>

      <p class="lead">This is the index page for an example Flask app using Bootstrap and WTForms</p>

      {{ render_form(form) }}

      <p class="pt-5"><strong>{{ message }}</strong></p>

    </div>
  </div>
</div>
{% endblock %}

hello-flask/studenst-flask/src/templates/students.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>User listing</title>
    <style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 30%;
}
td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}
tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>
<body>
    <h1>User listing</h1>
<table>
  <tr>
    <th>delete</th>
    <th>edit</th>
    <th>name</th>
    <th>registration</th>
  </tr>
  {% for student in students_list %}
  <tr>
    <th>
      <form 
      action="{{ url_for('students.student_delete', student_id=student['_id']) }}" 
      method="get">
        <button type="submit">delete</button>
      </form>
    </th>
    <th>
      <form 
      action="{{ url_for('students.student_edit', student_id=student['_id']) }}" 
      method="get">
        <button type="submit">Edit</button>
      </form>
    </th>
    <th>{{student["name"]}}</th>
    <th>{{student["registration"]}}</th>
  </tr>
  {% endfor %}
</table>
</body>
</html>